#!/usr/bin/env python3
"""Reproduce manuscript Figures 3--4 and Supplementary Figure S1.

Inputs are generated by ``run_wci_pdlr_analysis.py`` and stored in the clean
repository layout. Each panel plots only cases eligible for the quantity shown;
the ten-case audit remains preserved in the tabular outputs.
"""

from __future__ import annotations

import csv
import hashlib
import math
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from matplotlib.ticker import FuncFormatter
ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
RESULTS_DIR = ROOT / "results"
FIGURES_DIR = ROOT / "figures"
ANCHORS_CSV = RESULTS_DIR / "wci_pdlr_comparative_results.csv"
SCENARIOS_CSV = RESULTS_DIR / "wci_pdlr_scenario_results.csv"
EVIDENCE_CSV = RESULTS_DIR / "wci_evidence_status.csv"
PROVENANCE_CSV = DATA_DIR / "wci_input_provenance.csv"
SENSITIVITY_CSV = RESULTS_DIR / "wci_pdlr_analytic_sensitivity.csv"
SYNTHETIC_CSV = RESULTS_DIR / "wci_synthetic_boundary_tests.csv"
COMMUNITY_CSV = DATA_DIR / "community_context_inputs.csv"

SITE_ORDER = [
    "Lebanon", "Council Bluffs", "Mayes County", "The Dalles",
    "Douglas County", "Wisconsin site", "Botetourt County",
    "Memphis", "Midlothian", "Henderson",
]

DISPLAY_NAME = {
    "Wisconsin site": "Mount Pleasant, WI",
}


def display_name(site: str) -> str:
    return DISPLAY_NAME.get(site, site)

BLUE = "#2E79A8"
LIGHT_BLUE = "#A9CFE6"
DARK_BLUE = "#155F8A"
RED = "#C53A2C"
ORANGE = "#F47A20"
PURPLE = "#8D63B3"
GREY = "#B8BDC3"
DARK_GREY = "#5B6066"
PALE_GREY = "#EEF0F2"
GREEN = "#3E8E6E"

# Publication typography. Figures are designed for reduction to full journal
# page width, so source text is deliberately larger than screen-default sizes.
FONT_BASE = 14.0
FONT_AXIS = 18.0
FONT_XTICK = 15.0
FONT_YTICK = 16.0
FONT_LEGEND = 13.0
FONT_PANEL = 27.0
FONT_ANNOT = 12.5
FONT_NOTE = 11.0
FONT_CASE = 12.0

LAYOUT_AUDIT_ROWS: list[dict[str, str | float]] = []


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def as_float(value: str | None) -> float | None:
    if value is None or value.strip() == "":
        return None
    return float(value)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def configure_style() -> None:
    mpl.rcParams.update({
        "font.family": "serif",
        "font.serif": ["DejaVu Serif"],
        "font.size": FONT_BASE,
        "font.weight": "bold",
        "axes.labelsize": FONT_AXIS,
        "axes.labelweight": "bold",
        "xtick.labelsize": FONT_XTICK,
        "ytick.labelsize": FONT_YTICK,
        "legend.fontsize": FONT_LEGEND,
        "axes.linewidth": 1.25,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "savefig.facecolor": "white",
    })


def style_axis(ax, grid_axis="x") -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(axis=grid_axis, color="#E4E6E8", linewidth=1.0, zorder=0)
    ax.tick_params(width=1.2, length=5)
    for tick_label in [*ax.get_xticklabels(), *ax.get_yticklabels()]:
        tick_label.set_fontweight("bold")


def style_legend(legend) -> None:
    """Make every legend readable after reduction to journal-page width."""
    for legend_text in legend.get_texts():
        legend_text.set_fontweight("bold")
        legend_text.set_fontsize(FONT_LEGEND)
    legend.get_frame().set_linewidth(1.0)
    legend.get_frame().set_alpha(0.96)


def panel_label(ax, label: str, *, x: float = -0.075, y: float = 1.035) -> None:
    ax.text(x, y, label, transform=ax.transAxes, fontsize=FONT_PANEL,
            fontweight="bold", ha="left", va="bottom", clip_on=False)


def audit_text_layout(fig, stem: str) -> None:
    """Record visible text or legend intersections before tight export."""
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    texts = []
    for artist in fig.findobj(mpl.text.Text):
        if not artist.get_visible() or not artist.get_text().strip():
            continue
        # Matplotlib retains out-of-range tick artists even though the axes clip
        # them at export. Excluding those prevents false boundary collisions.
        bbox = artist.get_window_extent(renderer=renderer)
        centre_x = 0.5 * (bbox.x0 + bbox.x1)
        centre_y = 0.5 * (bbox.y0 + bbox.y1)
        x_owner = next((ax for ax in fig.axes
                        if artist in ax.get_xticklabels(which="both")), None)
        y_owner = next((ax for ax in fig.axes
                        if artist in ax.get_yticklabels(which="both")), None)
        if x_owner is not None:
            if centre_x < x_owner.bbox.x0 - 2 or centre_x > x_owner.bbox.x1 + 2:
                continue
        if y_owner is not None:
            if centre_y < y_owner.bbox.y0 - 2 or centre_y > y_owner.bbox.y1 + 2:
                continue
        texts.append(artist)
    boxes = []
    for artist in texts:
        bbox = artist.get_window_extent(renderer=renderer)
        if math.isfinite(bbox.x0) and math.isfinite(bbox.y0):
            boxes.append((artist, bbox))

    legends = fig.findobj(mpl.legend.Legend)
    for left_idx, (left_artist, left_bbox) in enumerate(boxes):
        for right_artist, right_bbox in boxes[left_idx + 1:]:
            if any(left_artist in legend.get_texts() and right_artist in legend.get_texts()
                   for legend in legends):
                continue
            overlap_x = min(left_bbox.x1, right_bbox.x1) - max(left_bbox.x0, right_bbox.x0)
            overlap_y = min(left_bbox.y1, right_bbox.y1) - max(left_bbox.y0, right_bbox.y0)
            if overlap_x >= 4.0 and overlap_y >= 4.0:
                LAYOUT_AUDIT_ROWS.append({
                    "figure": stem,
                    "issue": "text intersection",
                    "artist_a": left_artist.get_text().replace("\n", " / "),
                    "artist_b": right_artist.get_text().replace("\n", " / "),
                    "overlap_width_px": round(overlap_x, 2),
                    "overlap_height_px": round(overlap_y, 2),
                })

    for legend in legends:
        legend_bbox = legend.get_window_extent(renderer=renderer)
        legend_texts = set(legend.get_texts())
        for artist, text_bbox in boxes:
            if artist in legend_texts:
                continue
            overlap_x = min(legend_bbox.x1, text_bbox.x1) - max(legend_bbox.x0, text_bbox.x0)
            overlap_y = min(legend_bbox.y1, text_bbox.y1) - max(legend_bbox.y0, text_bbox.y0)
            if overlap_x >= 4.0 and overlap_y >= 4.0:
                LAYOUT_AUDIT_ROWS.append({
                    "figure": stem,
                    "issue": "legend/text intersection",
                    "artist_a": "Legend",
                    "artist_b": artist.get_text().replace("\n", " / "),
                    "overlap_width_px": round(overlap_x, 2),
                    "overlap_height_px": round(overlap_y, 2),
                })


def save_figure(fig, stem: str) -> None:
    audit_text_layout(fig, stem)
    fig.savefig(FIGURES_DIR / f"{stem}.pdf", bbox_inches="tight", pad_inches=0.04)
    fig.savefig(FIGURES_DIR / f"{stem}.jpg", dpi=600, bbox_inches="tight", pad_inches=0.04)
    plt.close(fig)


def anchor_rows() -> list[dict[str, str]]:
    rows = read_csv(ANCHORS_CSV)
    by_site = {row["site_name"]: row for row in rows}
    if set(by_site) != set(SITE_ORDER):
        raise ValueError("Comparative anchor file must contain the declared ten sites exactly")
    return [by_site[site] for site in SITE_ORDER]


def demand_basis(row: dict[str, str]) -> str:
    """Select the plotted flow basis from the scenario's declared calculation route.

    A directly reported peak takes precedence over an incidental average field only
    when the controlling scenario metadata explicitly identifies the direct-peak
    branch. This avoids site-name rules and prevents a reported peak from being
    misrepresented as an average-times-PF case.
    """
    route_note = (row.get("shared_pf_or_constant_r_assumption") or "").casefold()
    w_avg = as_float(row.get("W_avg_MGD"))
    w_peak = as_float(row.get("W_peak_MGD"))
    if "direct peak input" in route_note:
        if w_peak is None:
            raise ValueError(
                f"Scenario {row.get('scenario_id', '<unknown>')} declares a direct peak "
                "but has no W_peak_MGD"
            )
        return "direct_peak"
    if w_avg is not None:
        return "average"
    if w_peak is not None:
        raise ValueError(
            f"Scenario {row.get('scenario_id', '<unknown>')} has W_peak_MGD but does not "
            "declare the direct-peak calculation route"
        )
    return "unresolved"


def evidence_label(row: dict[str, str]) -> str:
    status = row["boundary_status"]
    rank = row["rank_admissibility"]
    if status == "fail":
        return "denominator ineligible"
    if status == "regional":
        return "regional K"
    if "confirmation_pending" in rank:
        return "confirm K"
    if rank == "scenario_only":
        return "planning"
    if rank == "conditional_scenario":
        return "assumed PF"
    return status


def build_figure_3() -> None:
    anchors = anchor_rows()
    community = read_csv(COMMUNITY_CSV)
    community_by_site = {row["site_name"]: row for row in community}
    if set(community_by_site) != set(SITE_ORDER):
        raise ValueError("Community audit must contain the declared ten sites exactly")

    eligible_anchors = [
        row for row in anchors
        if as_float(row["WCI"]) is not None and as_float(row["PDLR"]) is not None
    ]
    eligible_community = [
        community_by_site[site] for site in SITE_ORDER
        if as_float(community_by_site[site].get("community_share_pct")) is not None
    ]
    if len(eligible_anchors) != 10 or len(eligible_community) != 6:
        raise ValueError("Figure 3 requires ten ratio-eligible and six community-eligible cases")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(17.0, 6.4),
                                   gridspec_kw={"wspace": 0.42})
    y1 = np.arange(len(eligible_anchors))
    max_ref = max([100 * as_float(r["PDLR"]) for r in eligible_anchors] + [100])

    for idx, row in enumerate(eligible_anchors):
        wci = as_float(row["WCI"])
        pdlr = as_float(row["PDLR"])
        assert wci is not None and pdlr is not None
        color = RED if wci >= 1 else BLUE
        if row["boundary_status"] == "regional":
            color = LIGHT_BLUE
        ax1.barh(idx, 100 * wci, height=0.56, color=color,
                 edgecolor="#303030", linewidth=0.7, zorder=2)
        ax1.plot(100 * pdlr, idx, marker="D", ms=7.4, mfc="white",
                 mec="#222222", mew=1.4, linestyle="none", zorder=4)

    ax1.axvline(100, color=RED, linestyle="--", linewidth=1.6, zorder=1)
    ax1.set_yticks(y1, [display_name(row["site_name"]) for row in eligible_anchors],
                   fontweight="bold")
    ax1.invert_yaxis()
    ax1.set_xlim(0, max_ref * 1.08)
    ax1.set_xlabel("WCI and PDLR (% of declared capacity scale)", fontsize=16)
    style_axis(ax1)
    legend1 = ax1.legend(handles=[
        Patch(facecolor=BLUE, edgecolor="#303030", label="WCI"),
        Line2D([0], [0], marker="D", color="none", markerfacecolor="white",
               markeredgecolor="#222222", label="PDLR", markersize=7.4),
        Line2D([0], [0], color=RED, linestyle="--", label="Unity reference"),
    ], loc="upper center", bbox_to_anchor=(0.5, -0.19), ncol=3, frameon=True)
    style_legend(legend1)
    panel_label(ax1, "(a)", x=-0.09, y=1.08)

    y2 = np.arange(len(eligible_community))
    for idx, row in enumerate(eligible_community):
        share = as_float(row.get("community_share_pct"))
        jurisdiction = row.get("jurisdiction_type", "")
        assert share is not None
        ax2.barh(idx, share, height=0.56, color=BLUE,
                 edgecolor="#303030", linewidth=0.7, zorder=2)
        ax2.text(share, idx, f"  {share:.1f}% ({jurisdiction})", va="center",
                 ha="left", fontsize=FONT_ANNOT, fontweight="bold")
    ax2.set_yticks(y2, [display_name(row["site_name"]) for row in eligible_community],
                   fontweight="bold")
    ax2.invert_yaxis()
    numeric = [as_float(r.get("community_share_pct")) for r in eligible_community]
    ax2.set_xlim(0, max(numeric + [1]) * 1.30)
    ax2.set_xlabel(
        "Consumption (% of residential-use equivalent)", fontsize=16
    )
    style_axis(ax2)
    panel_label(ax2, "(b)")
    save_figure(fig, "Figure_3ab_WCI")


def build_figure_4() -> None:
    anchors = anchor_rows()
    community = read_csv(COMMUNITY_CSV)
    community_by_site = {row["site_name"]: row for row in community}
    provenance = read_csv(PROVENANCE_CSV)
    provenance_by_scenario: dict[str, dict[str, float | None]] = {}
    for row in provenance:
        provenance_by_scenario.setdefault(row["scenario_id"], {})[row["parameter"]] = as_float(row["central_value"])
    eligible_community = [
        community_by_site[site] for site in SITE_ORDER
        if as_float(community_by_site[site].get("household_equivalents")) is not None
    ]
    if len(eligible_community) != 6:
        raise ValueError("Figure 4b requires six community-eligible cases")
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(17.0, 6.2),
                                   gridspec_kw={"wspace": 0.42})
    y = np.arange(len(SITE_ORDER))
    ax1_pf = ax1.twiny()

    flow_k_values, flow_modes, r_values, pf_values = [], [], [], []
    for row in anchors:
        w_avg = as_float(row.get("W_avg_MGD"))
        w_peak = as_float(row.get("W_peak_MGD"))
        k = as_float(row.get("K_MGD"))
        basis = demand_basis(row)
        if basis == "average" and k is not None:
            flow_k_values.append(w_avg / k)
            flow_modes.append("average")
        elif basis == "direct_peak" and k is not None:
            flow_k_values.append(w_peak / k)
            flow_modes.append("direct_peak")
        else:
            flow_k_values.append(None)
            flow_modes.append("unresolved")
        r_value = as_float(row.get("r_used"))
        if r_value is None and w_avg not in (None, 0):
            c_avg = as_float(row.get("C_avg_MGD"))
            r_value = c_avg / w_avg if c_avg is not None else None
        r_values.append(r_value)
        pf = as_float(row.get("PF_W")) or as_float(row.get("PF_C"))
        if pf is None:
            pf = provenance_by_scenario.get(row["scenario_id"], {}).get("PF_shared")
        pf_values.append(pf)

    for idx in y:
        if flow_k_values[idx] is not None:
            hatch = "///" if flow_modes[idx] == "direct_peak" else None
            ax1.barh(idx + 0.20, flow_k_values[idx], height=0.24, color=BLUE,
                     edgecolor="#303030", linewidth=0.7, hatch=hatch, zorder=2)
        if r_values[idx] is not None:
            ax1.barh(idx - 0.20, r_values[idx], height=0.24, color=ORANGE,
                     edgecolor="#303030", linewidth=0.7, zorder=2)
        if pf_values[idx] is not None:
            ax1_pf.plot(pf_values[idx], idx, marker="o", ms=7.2, mfc=PURPLE,
                        mec="#4C3167", mew=1.0, linestyle="none", zorder=4)
    site_labels = [display_name(site) for site in SITE_ORDER]
    ax1.set_yticks(y, site_labels, fontweight="bold")
    ax1.invert_yaxis()
    ax1.set_xlim(0, max([v for v in flow_k_values + r_values if v is not None] + [1]) * 1.08)
    ax1.set_xlabel("Factor value (flow/K and r)")
    style_axis(ax1)
    ax1_pf.set_ylim(ax1.get_ylim())
    ax1_pf.set_xlim(0.8, max([v for v in pf_values if v is not None] + [3]) * 1.08)
    ax1_pf.tick_params(axis="y", left=False, right=False,
                       labelleft=False, labelright=False)
    ax1_pf.set_xlabel("PF (when defined)", color=PURPLE, labelpad=7)
    ax1_pf.xaxis.set_label_position("top")
    ax1_pf.xaxis.tick_top()
    ax1_pf.tick_params(axis="x", colors=PURPLE, width=1.2, length=5,
                       labelsize=FONT_XTICK)
    for tick_label in ax1_pf.get_xticklabels():
        tick_label.set_fontweight("bold")
    ax1_pf.spines["right"].set_visible(False)
    legend1 = ax1.legend(handles=[
        Patch(facecolor=BLUE, edgecolor="#303030", label="Wavg/K"),
        Patch(facecolor=BLUE, edgecolor="#303030", hatch="///", label="Wpeak/K (direct)"),
        Patch(facecolor=ORANGE, edgecolor="#303030", label="r"),
        Line2D([0], [0], marker="o", color="none", markerfacecolor=PURPLE,
               markeredgecolor="#4C3167", label="PF", markersize=7.2),
    ], loc="lower right", ncol=2, frameon=True)
    style_legend(legend1)
    panel_label(ax1, "(a)", x=-0.09, y=1.08)

    y2 = np.arange(len(eligible_community))
    for idx, row in enumerate(eligible_community):
        hh = as_float(row.get("household_equivalents"))
        jurisdiction = row.get("jurisdiction_type", "")
        assert hh is not None
        ax2.barh(idx, hh, height=0.56, color=LIGHT_BLUE,
                 edgecolor="#303030", linewidth=0.7, zorder=2)
        ax2.text(hh, idx, f"  {hh:,.0f} ({jurisdiction})", va="center",
                 ha="left", fontsize=FONT_ANNOT, fontweight="bold")
    ax2.set_yticks(y2, [display_name(row["site_name"]) for row in eligible_community],
                   fontweight="bold")
    ax2.invert_yaxis()
    hhs = [as_float(r.get("household_equivalents")) for r in eligible_community]
    ax2.set_xlim(0, max(hhs + [1]) * 1.30)
    ax2.set_xlabel("Household-use equivalents (thousands)")
    style_axis(ax2)
    ax2.xaxis.set_major_formatter(FuncFormatter(lambda value, _: f"{value / 1000:g}"))
    panel_label(ax2, "(b)", x=0.0, y=1.025)
    save_figure(fig, "Figure_4ab_Decomposition")


def build_figure_5() -> None:
    sensitivity = read_csv(SENSITIVITY_CSV)
    synthetic = read_csv(SYNTHETIC_CSV)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(17.0, 5.55),
                                   gridspec_kw={"wspace": 0.205})
    fig.subplots_adjust(bottom=0.225, top=0.94)

    parameters = ["W_or_peak", "r", "PF", "K"]
    labels = ["Demand or direct peak", "Consumptive ratio r", "Peaking factor PF", "Capacity scale K"]
    colors = [BLUE, ORANGE, PURPLE, GREY]
    y = np.arange(len(parameters))
    for idx, (parameter, color) in enumerate(zip(parameters, colors)):
        rows = [r for r in sensitivity if r["metric"] == "WCI" and r["parameter"] == parameter
                and r["perturbation_pct"] == "25"]
        dec = next(float(r["output_change_pct"]) for r in rows if r["direction"] == "decrease")
        inc = next(float(r["output_change_pct"]) for r in rows if r["direction"] == "increase")
        ax1.barh(idx, dec, height=0.44, color=color, alpha=0.78,
                 edgecolor="#303030", linewidth=0.7, zorder=2)
        ax1.barh(idx, inc, height=0.44, color=color,
                 edgecolor="#303030", linewidth=0.7, zorder=2)
        ax1.text(dec - 1.0 if dec < 0 else dec + 1.0, idx, f"{dec:+.1f}%",
                 va="center", ha="right" if dec < 0 else "left",
                 fontsize=FONT_ANNOT, fontweight="bold")
        inc_label_x = inc - 2.6 if parameter == "K" else inc + 1.0
        inc_label_ha = "right" if parameter == "K" else "left"
        ax1.text(inc_label_x, idx, f"{inc:+.1f}%",
                 va="center", ha=inc_label_ha,
                 fontsize=FONT_ANNOT, fontweight="bold")
    ax1.axvline(0, color="#222222", linewidth=1.25)
    ax1.set_yticks(y, labels, fontweight="bold")
    ax1.invert_yaxis()
    ax1.set_xlim(-40, 42)
    ax1.set_xlabel("Change in WCI under a ±25% input perturbation")
    style_axis(ax1)
    panel_label(ax1, "(a)")

    by_key = {(r["test_id"], r["case_id"]): r for r in synthetic}
    cases = [
        ("Dry cooling", by_key[("dry_cooling_boundary", "r_zero")], "wci_pdlr"),
        ("Growth +20%;\nWUE −20%", by_key[("growth_decoupling", "load_up_20_wue_down_20")], "wci_pdlr"),
        ("Regional K", by_key[("denominator_boundary", "regional_K")], "wci_pdlr"),
        ("Local K", by_key[("denominator_boundary", "local_K")], "wci_pdlr"),
        ("Gross K", by_key[("available_headroom", "gross_capacity_ratio")], "wci_pdlr"),
        ("Available\nheadroom", by_key[("available_headroom", "gross_capacity_ratio")], "headroom"),
        ("Extreme PF", by_key[("extreme_peaking", "pf_30")], "wci_pdlr"),
    ]
    rank_cases = [
        ("Rank A\nbaseline", by_key[("rank_reversal", "site_A_baseline")], "rank"),
        ("Rank B\nbaseline", by_key[("rank_reversal", "site_B_baseline")], "rank"),
        ("Rank A\n−10% W", by_key[("rank_reversal", "site_A_after_10pct_W_drop")], "rank"),
    ]
    all_cases = cases + rank_cases
    y2 = np.arange(len(all_cases))
    for idx, (label, row, case_kind) in enumerate(all_cases):
        wci_value = as_float(row["WCI"])
        pdlr_value = as_float(row["PDLR"])
        if case_kind == "wci_pdlr" and wci_value is not None and pdlr_value is not None and wci_value > 0:
            ax2.plot([wci_value, pdlr_value], [idx, idx], color="#8A8F94", lw=1.0, zorder=1)
        if case_kind == "headroom":
            headroom_value = as_float(row["auxiliary_value"])
            ax2.plot(headroom_value, idx, marker="^", ms=8.0, mfc=ORANGE,
                     mec="#7A3D0B", mew=1.0, linestyle="none", zorder=3)
            ax2.text(headroom_value * 1.06, idx, "peak/headroom", va="center",
                     ha="left", fontsize=FONT_NOTE, fontweight="bold",
                     color="#7A3D0B")
        elif wci_value == 0:
            ax2.plot(0.0075, idx, marker="x", ms=8.0, mew=1.8, color=BLUE,
                     linestyle="none", zorder=3)
            ax2.text(0.0082, idx, "WCI = 0", va="center", ha="left",
                     fontsize=FONT_NOTE, fontweight="bold", color=BLUE)
        elif wci_value is not None:
            ax2.plot(wci_value, idx, marker="s", ms=7.4, mfc=BLUE, mec="#303030",
                     mew=0.7, linestyle="none", zorder=3)
        if case_kind == "wci_pdlr" and pdlr_value is not None:
            ax2.plot(pdlr_value, idx, marker="D", ms=7.2, mfc="white", mec=DARK_BLUE,
                     mew=1.4, linestyle="none", zorder=3)
    ax2.axvline(1, color=RED, linestyle="--", linewidth=1.5, label="Unity reference")
    separator_y = len(cases) - 0.5
    ax2.axhline(separator_y, color="#9FA3A7", linestyle=":", linewidth=1.1)
    ax2.set_xscale("log")
    ax2.set_xlim(0.0065, 4.3)
    ax2.set_ylim(-0.65, len(all_cases) - 0.35)
    ax2.set_yticks(y2, [name for name, _, _ in all_cases],
                   fontsize=FONT_CASE, fontweight="bold")
    ax2.tick_params(axis="y", pad=3)
    ax2.invert_yaxis()
    ax2.set_xlabel("Synthetic ratio value (log scale)")
    style_axis(ax2, grid_axis="x")
    legend2 = ax2.legend(handles=[
        Line2D([0], [0], marker="s", color="none", markerfacecolor=BLUE,
               markeredgecolor="#303030", label="WCI", markersize=7.4),
        Line2D([0], [0], marker="D", color="none", markerfacecolor="white",
               markeredgecolor=DARK_BLUE, label="PDLR", markersize=7.2),
        Line2D([0], [0], marker="^", color="none", markerfacecolor=ORANGE,
               markeredgecolor="#7A3D0B", label="Peak/headroom", markersize=8.0),
        Line2D([0], [0], color=RED, linestyle="--", label="Unity reference"),
    ], loc="upper center", bbox_to_anchor=(0.5, -0.205),
       ncol=4, frameon=True, borderaxespad=0.0)
    style_legend(legend2)
    panel_label(ax2, "(b)", x=0.0, y=1.025)
    save_figure(fig, "Figure_S1_Sensitivity_FailureModes")


def write_manifest() -> None:
    inputs = [ANCHORS_CSV, SCENARIOS_CSV, EVIDENCE_CSV, PROVENANCE_CSV, SENSITIVITY_CSV,
              SYNTHETIC_CSV, COMMUNITY_CSV]
    outputs = sorted(
        path
        for path in [*FIGURES_DIR.glob("*.pdf"), *FIGURES_DIR.glob("*.jpg")]
        if not path.name.startswith("._")
    )
    rows = ["role,file,sha256"]
    rows.extend(
        f"input,{p.relative_to(ROOT).as_posix()},{sha256(p)}" for p in inputs
    )
    rows.extend(
        f"output,{p.relative_to(ROOT).as_posix()},{sha256(p)}" for p in outputs
    )
    manifest_path = RESULTS_DIR / "figure_manifest.csv"
    with manifest_path.open("w", encoding="utf-8", newline="") as handle:
        handle.write("\n".join(rows) + "\n")


def write_layout_audit() -> None:
    fields = ["figure", "issue", "artist_a", "artist_b",
              "overlap_width_px", "overlap_height_px"]
    path = RESULTS_DIR / "figure_layout_audit.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(LAYOUT_AUDIT_ROWS)


def validate_inputs_and_outputs() -> None:
    anchors = anchor_rows()
    if sum(as_float(row["WCI"]) is not None for row in anchors) != 10:
        raise ValueError("Expected ten numeric WCI anchors in the ten-case audit")
    for row in anchors:
        basis = demand_basis(row)
        if basis != "direct_peak":
            continue
        w_peak = as_float(row.get("W_peak_MGD"))
        k = as_float(row.get("K_MGD"))
        pdlr = as_float(row.get("PDLR"))
        if k is not None and pdlr is not None and not math.isclose(
            w_peak / k, pdlr, rel_tol=0.0, abs_tol=1e-10
        ):
            raise ValueError(
                f"Direct-peak factor profile disagrees with PDLR for {row['site_name']}"
            )
    community = read_csv(COMMUNITY_CSV)
    if len(community) != 10:
        raise ValueError("Expected exactly ten community-context rows")
    if sum(as_float(row["community_share_pct"]) is not None for row in community) != 6:
        raise ValueError("Expected six numeric community shares in the ten-case audit")
    if sum(as_float(row["household_equivalents"]) is not None for row in community) != 6:
        raise ValueError("Expected six numeric household equivalents in the ten-case audit")

    pdf_paths = sorted(
        path for path in FIGURES_DIR.glob("*.pdf") if not path.name.startswith("._")
    )
    if len(pdf_paths) != 3:
        raise ValueError("Expected exactly three publication PDF outputs")
    for path in pdf_paths:
        if path.stat().st_size == 0 or path.read_bytes()[:4] != b"%PDF":
            raise ValueError(f"{path.name} is not a valid non-empty PDF")
    if LAYOUT_AUDIT_ROWS:
        raise ValueError(
            "Detected figure text-layout intersections; see results/figure_layout_audit.csv"
        )


def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    configure_style()
    required = [ANCHORS_CSV, SCENARIOS_CSV, EVIDENCE_CSV, PROVENANCE_CSV, SENSITIVITY_CSV,
                SYNTHETIC_CSV, COMMUNITY_CSV]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing audited figure input(s): " + ", ".join(missing))
    build_figure_3()
    build_figure_4()
    build_figure_5()
    write_manifest()
    write_layout_audit()
    validate_inputs_and_outputs()
    print("PASS: generated Figures 3--4 and Supplementary Figure S1 as vector PDFs.")


if __name__ == "__main__":
    main()
